# Start with a Node.js base image
FROM node:21

# Set the working directory
WORKDIR /app

# --- Node.js Setup ---

# Copy Node package files
# Assumes package.json is in the root of the build context (./backend)
COPY package*.json ./

# Install Node dependencies using clean install
RUN npm ci

# Copy the rest of the application code from the build context (./backend)
COPY . .

# --- Runtime Configuration ---
ENV PORT=7000
EXPOSE 7000

# Start the Node.js application
CMD ["node", "server.js"]