FROM node:21

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci

# Copy application code
COPY . .

# Set environment variables
ENV PORT=7000

# Expose the application port
EXPOSE 7000

# Start the application
CMD ["node", "server.js"]
